### ISSUE TITLE
第二周第4篇文章链接和第一周第3篇文章链接一样了

### ISSUE THREAD

**Issue by theprimone** [Tnfe/TNFE-Weekly#1]
> ## 第二周
> 4. [JavaScript Standard Style，2万star的规范](https://juejin.im/post/5c248f0ff265da611c270815)

> ## 第一周
> 3. [1位开发如何撑起一个过亿用户的小程序？](https://juejin.im/post/5c248f0ff265da611c270815)

**Comment by JN-H** [comment]
已修复
